### ISSUE TITLE
[Bug] Error code 100 during install

### ISSUE THREAD

**Issue by c3p0vsr2d2** [thor0215/hassio-xfinity-usage#17]
I am running a HomeAssistant VM through virtualbox. 

I see an Error code 100 during add-on install. The dialog message I see is:

The command '/bin/bash -o pipefail -c apt-get update && apt-get install -y --no-install-recommends ca-certificates=20230311ubuntu0.22.04.1 curl=7.81.0-1ubuntu1.16 jq=1.6-2.1ubuntu3 tzdata=2024a-0ubuntu0.22.04 xz-utils=5.2.5-2ubuntu1 && S6_ARCH="${BUILD_ARCH}" && if [ "${BUILD_ARCH}" = "i386" ]; then S6_ARCH="i686"; elif [ "${BUILD_ARCH}" = "amd64" ]; then S6_ARCH="x86_64"; elif [ "${BUILD_ARCH}" = "armv7" ]; then S6_ARCH="arm"; fi && curl -L -s "https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-noarch.tar.xz" | tar -C / -Jxpf - && curl -L -s "https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-${S6_ARCH}.tar.xz" | tar -C / -Jxpf - && curl -L -s "https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-symlinks-noarch.tar.xz" | tar -C / -Jxpf - && curl -L -s "https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-symlinks-arch.tar.xz" | tar -C / -Jxpf - && mkdir -p /etc/fix-attrs.d && mkdir -p /etc/services.d && curl -J -L -o /tmp/bashio.tar.gz "https://github.com/hassio-addons/bashio/archive/${BASHIO_VERSION}.tar.gz" && mkdir /tmp/bashio && tar zxvf /tmp/bashio.tar.gz --strip 1 -C /tmp/bashio && mv /tmp/bashio/lib /usr/lib/bashio && ln -s /usr/lib/bashio/bashio /usr/bin/bashio && curl -L -s -o /usr/bin/tempio "https://github.com/home-assistant/tempio/releases/download/${TEMPIO_VERSION}/tempio_${BUILD_ARCH}" && chmod a+x /usr/bin/tempio && apt-get purge -y --auto-remove xz-utils && apt-get clean && rm -fr /tmp/* /var/{cache,log}/* /var/lib/apt/lists/*' returned a non-zero code: 100

**Comment by thor0215** [comment]
Try the latest version 0.0.12 and let me know if you have any more issues.

**Comment by c3p0vsr2d2** [comment]
Thanks for the quick fix.
Installing 0.0.12, and I see the spinning install logo the past 5 minutes. Does it typically take this long to finish?

**Comment by thor0215** [comment]
It does take some time to download the Ubuntu docker image, update it,
download the s6-overlay, and apply that. Then it installs various Python
dependencies, Playwright, and Playwright Firefox build.  You can monitor
the build process by going to HA Settings, System, Logs, then select
Supervisor from the upper right pull down.  Click the refresh button to
reload the logs.

**Comment by c3p0vsr2d2** [comment]
thanks @thor0215 - Install finally finished without issues. I am facing some MQTT hiccups, which I will work on sorting out. Please close this issue, and thanks again for the super quick turnaround.
