### ISSUE TITLE
Provide pre-built containers

### ISSUE THREAD

**Issue by tronikos** [thor0215/hassio-xfinity-usage#23]
See https://developers.home-assistant.io/docs/add-ons/publishing#pre-built-containers
It's much faster to start using a pre-built container and backups are much smaller since they don't have to include the locally built container.
You can use github workflows to simplify the process such as https://github.com/home-assistant/addons-example/blob/main/.github/workflows/builder.yaml

**Comment by thor0215** [comment]
I will consider this in the future.

**Comment by thor0215** [comment]
0.0.12.7.2 is now using prebuilt containers. Let me know if you have any issues.  Github actions are pretty cool and not too hard to implement so thanks for the push :)

**Comment by tronikos** [comment]
Thanks! It's working fine. My last backup was much smaller. But it can be even smaller by excluding Firefox profile directories. There is no need to back those up. I'll send you a PR.
