### ISSUE TITLE
Can’t connect after updating to 2024.11.0

### ISSUE THREAD

**Issue by kartcon** [thor0215/hassio-xfinity-usage#49]
Things I’ve tried:
Restart add on, restart Home Assistant
Re-enter user name and password, re-entered MQTT password from logs
Reboot xfinity modem, reboot Ubiquity router.
This error started after upgrade to HA 2024-11, which I installed on 11/7/24.

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting
-----------------------------------------------------------
 Add-on: Xfinity Internet Usage
 Get Xfinity Internet Usage Data
-----------------------------------------------------------
 Add-on version: 0.0.12.8.2
 You are running the latest version of this add-on.
 System: Home Assistant OS 13.2  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2024.11.0
 Home Assistant Supervisor: 2024.11.2
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-timezone: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
[07:43:12] INFO: Configuring timezone (America/New_York)...
Log level is set to INFO
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service base-addon-timezone successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
---
MQTT addon is active on your system!
Add the MQTT details below to the addon configuration :
MQTT user : addons
MQTT password : ieY4uwahchi9aeloo8void4taez1oom1oD8waiThaengeey0nai3aisa0coh6ta8
MQTT Hostname : core-mosquitto
MQTT Port : 1883
---
2024-11-08T07:43:19.638 INFO: Connected to MQTT Broker!
2024-11-08T07:43:19.639 INFO: Xfinity Internet Usage Starting
2024-11-08T07:43:25.521 INFO: Launching Mozilla/5.0 (Android 10; Mobile; rv:121.0) Gecko/121.0 Firefox/121.0
2024-11-08T07:43:31.051 INFO: Loading Xfinity Authentication (URL: https://login.xfinity.com/login)
2024-11-08T07:43:33.175 WARNING: Retrying __main__.run_playwright in 1.0 seconds as it raised AssertionError: Password form page is missing the user id.
2024-11-08T07:43:34.177 WARNING: 1st retry
2024-11-08T07:43:39.879 INFO: Launching Mozilla/5.0 (Android 10; Mobile; rv:124.0) Gecko/124.0 Firefox/124.0
2024-11-08T07:43:45.596 INFO: Loading Xfinity Authentication (URL: https://login.xfinity.com/login)
2024-11-08T07:43:47.834 WARNING: Retrying __main__.run_playwright in 2.0 seconds as it raised AssertionError: Password form page is missing the user id.
2024-11-08T07:43:49.836 WARNING: 2nd retry
2024-11-08T07:43:55.574 INFO: Launching Mozilla/5.0 (Android 10; Mobile; rv:124.0) Gecko/124.0 Firefox/124.0
2024-11-08T07:44:00.784 INFO: Loading Xfinity Authentication (URL: https://login.xfinity.com/login)
2024-11-08T07:44:02.960 WARNING: Retrying __main__.run_playwright in 4.0 seconds as it raised AssertionError: Password form page is missing the user id.
2024-11-08T07:44:06.965 WARNING: 3rd retry
2024-11-08T07:44:12.793 INFO: Launching Mozilla/5.0 (Android 10; Mobile; rv:123.0) Gecko/123.0 Firefox/123.0
2024-11-08T07:44:17.820 INFO: Loading Xfinity Authentication (URL: https://login.xfinity.com/login)
2024-11-08T07:44:20.155 WARNING: Retrying __main__.run_playwright in 8.0 seconds as it raised AssertionError: Password form page is missing the user id.
2024-11-08T07:44:28.161 WARNING: 4th retry
2024-11-08T07:44:33.962 INFO: Launching Mozilla/5.0 (Android 10; Mobile; rv:121.0) Gecko/121.0 Firefox/121.0
2024-11-08T07:44:39.697 INFO: Loading Xfinity Authentication (URL: https://login.xfinity.com/login)
2024-11-08T07:44:41.712 WARNING: Retrying __main__.run_playwright in 15.0 seconds as it raised AssertionError: Password form page is missing the user id.

**Comment by thor0215** [comment]
Check and see if the newest v0.1.0 fixes the issue or not.

**Comment by kartcon** [comment]
Nope. Still getting same error in logs. Like the colors BTW.starting----------------------------------------------------------- Add-on: Xfinity Internet Usage Get Xfinity Internet Usage Data----------------------------------------------------------- Add-on version: 0.1.0 You are running the latest version of this add-on. System: Home Assistant OS 13.2  (aarch64 / raspberrypi4-64) Home Assistant Core: 2024.11.0 Home Assistant Supervisor: 2024.11.2----------------------------------------------------------- Please, share the above information when looking for help or support in, e.g., GitHub, forums or the Discord chat.-----------------------------------------------------------s6-rc: info: service base-addon-banner successfully starteds6-rc: info: service fix-attrs: startings6-rc: info: service base-addon-timezone: startings6-rc: info: service base-addon-log-level: startings6-rc: info: service fix-attrs successfully started[14:48:54] INFO: Configuring timezone (America/New_York)...Log level is set to INFOs6-rc: info: service base-addon-log-level successfully starteds6-rc: info: service base-addon-timezone successfully starteds6-rc: info: service legacy-cont-init: startings6-rc: info: service legacy-cont-init successfully starteds6-rc: info: service legacy-services: startings6-rc: info: service legacy-services successfully started---MQTT addon is active on your system!Add the MQTT details below to the addon configuration :MQTT user : addonsMQTT password : ieY4uwahchi9aeloo8void4taez1oom1oD8waiThaengeey0nai3aisa0coh6ta8MQTT Hostname : core-mosquittoMQTT Port : 1883---2024-11-08T14:49:02.436 INFO: Xfinity Internet Usage Starting2024-11-08T14:49:02.920 INFO: Connected to MQTT Broker!2024-11-08T14:49:10.075 INFO: Launching Mozilla/5.0 (Android 10; Mobile; rv:123.0) Gecko/123.0 Firefox/123.02024-11-08T14:49:16.688 INFO: Loading Xfinity Authentication (URL: https://login.xfinity.com/login)2024-11-08T14:49:18.858 WARNING: Retrying __main__.run_playwright in 1.0 seconds as it raised AssertionError: Password form page is missing the user id.2024-11-08T14:49:19.861 WARNING: 1st retry2024-11-08T14:49:25.695 INFO: Launching Mozilla/5.0 (Android 10; Mobile; rv:120.0) Gecko/120.0 Firefox/120.02024-11-08T14:49:31.968 INFO: Loading Xfinity Authentication (URL: https://login.xfinity.com/login)2024-11-08T14:49:34.198 WARNING: Retrying __main__.run_playwright in 2.0 seconds as it raised AssertionError: Password form page is missing the user id.2024-11-08T14:49:36.201 WARNING: 2nd retry2024-11-08T14:49:42.206 INFO: Launching Mozilla/5.0 (Android 10; Mobile; rv:122.0) Gecko/122.0 Firefox/122.02024-11-08T14:49:47.883 INFO: Loading Xfinity Authentication (URL: https://login.xfinity.com/login)2024-11-08T14:49:50.781 WARNING: Retrying __main__.run_playwright in 4.0 seconds as it raised AssertionError: Password form page is missing the user id.2024-11-08T14:49:54.787 WARNING: 3rd retry2024-11-08T14:50:00.608 INFO: Launching Mozilla/5.0 (Android 10; Mobile; rv:122.0) Gecko/122.0 Firefox/122.02024-11-08T14:50:06.569 INFO: Loading Xfinity Authentication (URL: https://login.xfinity.com/login)2024-11-08T14:50:08.616 WARNING: Retrying __main__.run_playwright in 8.0 seconds as it raised AssertionError: Password form page is missing the user id.2024-11-08T14:50:16.625 WARNING: 4th retry2024-11-08T14:50:22.368 INFO: Launching Mozilla/5.0 (Android 10; Mobile; rv:122.0) Gecko/122.0 Firefox/122.02024-11-08T14:50:28.297 INFO: Loading Xfinity Authentication (URL: https://login.xfinity.com/login)2024-11-08T14:50:30.640 WARNING: Retrying __main__.run_playwright in 15.0 seconds as it raised AssertionError: Password form page is missing the user id.Art DavisSent from my iPadOn Nov 8, 2024, at 2:29 PM, thor0215 ***@***.***> wrote:﻿
Check and see if the newest v0.1.0 fixes the issue or not.

**Comment by kartcon** [comment]
Bryan,One other thought. My WAN IP Address recently changed. Could that be a factor in this issue? I had to replace my old Ubiquity Cloud Key (which finally failed) with a new Unifi Dream Machine, so upon connecting to the XFinity modem, it assigned me a new WAN IP. All other inbound and outbound services work correctly, as does HA, Synology and a variety of other 3rd party cloud based apps. Thanks again for your help.Art DavisSent from my iPadOn Nov 8, 2024, at 2:51 PM, Art Davis ***@***.***> wrote:﻿Nope. Still getting same error in logs. Like the colors BTW.starting----------------------------------------------------------- Add-on: Xfinity Internet Usage Get Xfinity Internet Usage Data----------------------------------------------------------- Add-on version: 0.1.0 You are running the latest version of this add-on. System: Home Assistant OS 13.2  (aarch64 / raspberrypi4-64) Home Assistant Core: 2024.11.0 Home Assistant Supervisor: 2024.11.2----------------------------------------------------------- Please, share the above information when looking for help or support in, e.g., GitHub, forums or the Discord chat.-----------------------------------------------------------s6-rc: info: service base-addon-banner successfully starteds6-rc: info: service fix-attrs: startings6-rc: info: service base-addon-timezone: startings6-rc: info: service base-addon-log-level: startings6-rc: info: service fix-attrs successfully started[14:48:54] INFO: Configuring timezone (America/New_York)...Log level is set to INFOs6-rc: info: service base-addon-log-level successfully starteds6-rc: info: service base-addon-timezone successfully starteds6-rc: info: service legacy-cont-init: startings6-rc: info: service legacy-cont-init successfully starteds6-rc: info: service legacy-services: startings6-rc: info: service legacy-services successfully started---MQTT addon is active on your system!Add the MQTT details below to the addon configuration :MQTT user : addonsMQTT password : ieY4uwahchi9aeloo8void4taez1oom1oD8waiThaengeey0nai3aisa0coh6ta8MQTT Hostname : core-mosquittoMQTT Port : 1883---2024-11-08T14:49:02.436 INFO: Xfinity Internet Usage Starting2024-11-08T14:49:02.920 INFO: Connected to MQTT Broker!2024-11-08T14:49:10.075 INFO: Launching Mozilla/5.0 (Android 10; Mobile; rv:123.0) Gecko/123.0 Firefox/123.02024-11-08T14:49:16.688 INFO: Loading Xfinity Authentication (URL: https://login.xfinity.com/login)2024-11-08T14:49:18.858 WARNING: Retrying __main__.run_playwright in 1.0 seconds as it raised AssertionError: Password form page is missing the user id.2024-11-08T14:49:19.861 WARNING: 1st retry2024-11-08T14:49:25.695 INFO: Launching Mozilla/5.0 (Android 10; Mobile; rv:120.0) Gecko/120.0 Firefox/120.02024-11-08T14:49:31.968 INFO: Loading Xfinity Authentication (URL: https://login.xfinity.com/login)2024-11-08T14:49:34.198 WARNING: Retrying __main__.run_playwright in 2.0 seconds as it raised AssertionError: Password form page is missing the user id.2024-11-08T14:49:36.201 WARNING: 2nd retry2024-11-08T14:49:42.206 INFO: Launching Mozilla/5.0 (Android 10; Mobile; rv:122.0) Gecko/122.0 Firefox/122.02024-11-08T14:49:47.883 INFO: Loading Xfinity Authentication (URL: https://login.xfinity.com/login)2024-11-08T14:49:50.781 WARNING: Retrying __main__.run_playwright in 4.0 seconds as it raised AssertionError: Password form page is missing the user id.2024-11-08T14:49:54.787 WARNING: 3rd retry2024-11-08T14:50:00.608 INFO: Launching Mozilla/5.0 (Android 10; Mobile; rv:122.0) Gecko/122.0 Firefox/122.02024-11-08T14:50:06.569 INFO: Loading Xfinity Authentication (URL: https://login.xfinity.com/login)2024-11-08T14:50:08.616 WARNING: Retrying __main__.run_playwright in 8.0 seconds as it raised AssertionError: Password form page is missing the user id.2024-11-08T14:50:16.625 WARNING: 4th retry2024-11-08T14:50:22.368 INFO: Launching Mozilla/5.0 (Android 10; Mobile; rv:122.0) Gecko/122.0 Firefox/122.02024-11-08T14:50:28.297 INFO: Loading Xfinity Authentication (URL: https://login.xfinity.com/login)2024-11-08T14:50:30.640 WARNING: Retrying __main__.run_playwright in 15.0 seconds as it raised AssertionError: Password form page is missing the user id.Art DavisSent from my iPadOn Nov 8, 2024, at 2:29 PM, thor0215 ***@***.***> wrote:﻿
Check and see if the newest v0.1.0 fixes the issue or not.

**Comment by kartcon** [comment]
Bryan,Just did the HA 2024.11.1 update w no change in the Xfinity app. I did turn on debug mode after the restart and came across this line that doesn’t make sense to me.2024-11-08T15:37:16.408 DEBUG: <input id="user" name="user" type="text" autocomplete="username" ***@***.***" disabled="" class="hidden">Our UN should be turbosteff all l/c and I don’t recognize that email address. Just FYI. Let me know if this is too much info and I’ll just stand by while you troubleshoot.Art DavisSent from my iPadOn Nov 8, 2024, at 2:29 PM, thor0215 ***@***.***> wrote:﻿
Check and see if the newest v0.1.0 fixes the issue or not.

**Comment by thor0215** [comment]
Can you stop the Addon? Then go to the servers addon_configs/xfinity_usage folder and delete the profile folder. Then see if that fixes the addon.

**Comment by kartcon** [comment]
One last Screenshot
￼

**Comment by kartcon** [comment]
Bryan,

After nearly 2 hours on the phone with Xfinity, they were finally able to get my Xfinity modem to recognize the new Unify Dream Machine, get a new IP address that matched on both pieces of hardware and low and behold, the app works again. SO, in this case it was a hardware issue and not a software one. I do thank you for everything you do to maintain the app and support the HA community. Im sure it can be very frustrating in cases like this, especially for those folks who are less tech savvy.
Have a great weekend.

Art

**Comment by thor0215** [comment]
Thanks for the update and I'll go ahead and close the issue

**Comment by kartcon** [comment]
Bryan,
I’m not going to open another issue, but did want to show you in the logs what I've been seeing since shortly after you closed my original issue. The app will connect to Xfinity, download all the necessary data once, then it fails for up to 2 days repeatedly. Today I remembered to look at the logs and caught a section where it did connect, then fails. Since I noticed it was failing, I put the startup on an automation which attempts to start it a few times a day, usually when I expect the data to change. I was wondering if it was flooding the server with requests. Unfortunately, it didn’t make any difference. We switched over to the unlimited plan, so data use is less of a concern now, but I’m still bummed it doesn’t work consistently. I hope this may help.
Below are the logs (only basic).

-----------------------------------------------------------
 Add-on: Xfinity Internet Usage
 Get Xfinity Internet Usage Data
-----------------------------------------------------------
 Add-on version: 0.1.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 13.2  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2024.11.2
 Home Assistant Supervisor: 2024.11.2
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-timezone: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
[10:08:02] INFO: Configuring timezone (America/New_York)...
Log level is set to INFO
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service base-addon-timezone successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
---
MQTT addon is active on your system!
Add the MQTT details below to the addon configuration :
MQTT user : addons
MQTT password : ieY4uwahchi9aeloo8void4taez1oom1oD8waiThaengeey0nai3aisa0coh6ta8
MQTT Hostname : core-mosquitto
MQTT Port : 1883
---
2024-11-17T10:08:12.380 INFO: Xfinity Internet Usage Starting
2024-11-17T10:08:14.391 INFO: Updating Sensor: sensor.xfinity_usage
2024-11-17T10:08:27.680 INFO: Launching Mozilla/5.0 (Android 10; Mobile; rv:121.0) Gecko/121.0 Firefox/121.0
2024-11-17T10:08:35.491 INFO: Loading Xfinity Authentication (URL: https://login.xfinity.com/login)
2024-11-17T10:08:36.836 INFO: Entering username (URL: https://login.xfinity.com/login)
2024-11-17T10:08:50.930 INFO: Entering password (URL: https://login.xfinity.com/login)
2024-11-17T10:09:18.520 INFO: Updating Session Details
2024-11-17T10:09:32.520 INFO: Updating Session Details
2024-11-17T10:09:35.736 INFO: Loading Plan & Usage Data (URL: https://www.xfinity.com/learn/internet-service/auth)
2024-11-17T10:09:38.774 INFO: Updating Usage Details
2024-11-17T10:09:39.483 INFO: Updating Plan Details
2024-11-17T10:09:47.223 INFO: Usage data retrieved and processed
2024-11-17T10:09:47.223 INFO: Updating Sensor: sensor.xfinity_usage
2024-11-17T10:09:47.262 INFO: Updating Sensor File
2024-11-17T10:09:54.168 INFO: Updating Session Details
2024-11-17T10:10:18.900 INFO: Unloading Xfinity
2024-11-17T10:10:22.246 INFO: Sleeping for 3600 seconds
2024-11-17T11:10:23.866 INFO: Xfinity Internet Usage Starting
2024-11-17T11:10:24.867 INFO: Updating Sensor: sensor.xfinity_usage
2024-11-17T11:10:29.805 INFO: Launching Mozilla/5.0 (Android 10; Mobile; rv:121.0) Gecko/121.0 Firefox/121.0
2024-11-17T11:10:35.192 INFO: Loading Xfinity Authentication (URL: https://login.xfinity.com/login)
2024-11-17T11:10:36.967 INFO: Entering username (URL: https://login.xfinity.com/login)
2024-11-17T11:10:47.126 INFO: Entering password (URL: https://login.xfinity.com/login)
2024-11-17T11:11:13.126 INFO: Updating Session Details
2024-11-17T11:11:24.738 INFO: Updating Session Details
2024-11-17T11:11:26.866 INFO: Loading Plan & Usage Data (URL: https://www.xfinity.com/learn/internet-service/auth)
2024-11-17T11:11:28.404 INFO: Updating Plan Details
2024-11-17T11:11:30.327 INFO: Updating Usage Details
2024-11-17T11:11:35.859 INFO: Usage data retrieved and processed
2024-11-17T11:11:35.859 INFO: Updating Sensor: sensor.xfinity_usage
2024-11-17T11:11:35.895 INFO: Updating Sensor File
2024-11-17T11:11:42.870 INFO: Updating Session Details
2024-11-17T11:12:07.305 INFO: Unloading Xfinity
2024-11-17T11:12:09.653 INFO: Sleeping for 3600 seconds
2024-11-17T12:12:11.198 INFO: Xfinity Internet Usage Starting
2024-11-17T12:12:12.290 INFO: Updating Sensor: sensor.xfinity_usage
2024-11-17T12:12:17.040 INFO: Launching Mozilla/5.0 (Android 10; Mobile; rv:123.0) Gecko/123.0 Firefox/123.0
2024-11-17T12:12:23.310 INFO: Loading Xfinity Authentication (URL: https://login.xfinity.com/login)
2024-11-17T12:12:24.476 INFO: Entering username (URL: https://login.xfinity.com/login)
2024-11-17T12:12:35.726 INFO: Entering password (URL: https://login.xfinity.com/login)
2024-11-17T12:12:46.723 INFO: Entering password (URL: https://login.xfinity.com/login)
2024-11-17T12:12:58.902 ERROR: Navigated to password page for the  2nd time. Exiting...
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-timezone: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-timezone successfully stopped
s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting

This is the automation I use to (re)start it.
#################################################################
# Get XFinity Data
# https://github.com/thor0215/hassio-xfinity-usage
#################################################################
- id: restart_xfinity_sensors
  alias: Restart Xfinity Sensors
  initial_state: TRUE
  mode: single
  description: Restart Xfinity Internet Usage sensor
  triggers:
  - trigger: homeassistant
    event: start
  - platform: time
    at: '06:00:00'
  - platform: time
    at: '18:00:00'
  - platform: time
    at: '20:00:00'
  - platform: time
    at: '22:00:00'
  conditions:
  - condition: state
    entity_id: binary_sensor.xfinity_internet_usage_running
    state: 'off'
  actions:
  - action: hassio.addon_start
    data:
      addon: 989f231b_xfinity-usage

Art
