### ISSUE TITLE
Error logging in (ERROR: Navigated to password page for the  2nd time. Exiting...)

### ISSUE THREAD

**Issue by izzletodasmizzle** [thor0215/hassio-xfinity-usage#62]
I set up the add-on yesterday and was able to successfully retrieve my data usage and migrate it into HA that morning. However, after that first time, it now consistently gives the "ERROR:  Navigated to password page for the  2nd time. Exiting..." error. This continues 2-3 times before eventually hanging with high CPU/RAM usage. I have already attempted reinstalling the add-on (choosing to wipe data) as well as resetting my configs and reentering all info. I have also confirmed I am able to login with the credentials used in the config via my browser, and I do not have 2FA enabled. Attached are the debug logs. Thanks for this app, it is MUCH appreciated, wish Xfinity made it easier to track usage.

[logs.pdf](https://github.com/user-attachments/files/18187688/logs.pdf)

**Comment by izzletodasmizzle** [comment]
To add, not sure if my password should be in plain text in the logs (assume it should for XFINITY_PASSWORD) and if so, it appears that the add-on is ignoring my actual password in my config and replacing it with a string of random characters.

**Comment by J-CMartin** [comment]
I had luck with the new version for a few hours and it started failing again. Same problem.

**Comment by thor0215** [comment]
Let know if v0.1.2.2 helps.  Xfinity's bot detection is causing a lot of headaches.

**Comment by izzletodasmizzle** [comment]
> Let know if v0.1.2.2 helps. Xfinity's bot detection is causing a lot of headaches.

Yup, hat worked! Thank you for your work on this, much appreciated!
