### ISSUE TITLE
Unable to install add-on: returned a non-zero code 1

### ISSUE THREAD

**Issue by ghostbitmeta** [thor0215/hassio-xfinity-usage#7]
Hi, I get this error when trying to install the add-on. How to debug?
`2024-05-19 12:48:55.984 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /addons/15d584b4_xfinity-usage/install - The command '/bin/bash -o pipefail -c pip3 install --upgrade pip &&     pip3 install --no-cache-dir   --prefer-binary   typing-extensions==4.11.0   pyee==11.1.0   greenlet==3.0.3   tenacity==8.2.3   requests==2.31.0' returned a non-zero code: 1`

**Comment by thor0215** [comment]
Try installing it again and see if you still have that issue. It looks like the Python pip is failing to install the dependent Python libraries which could be an issue with internet access during that build process. I did rebuild the addon on my system and didn't have any problems. Let me know if you keep running into this issue.

**Comment by thor0215** [comment]
That is probably the problem, I do not include a 32 bit Ubuntu option in the build.yaml since there isn't a HA jammy docker image to use.
